title: "Deposit Tokens Comparison"
description: "A minimal Jekyll site displaying the comparison paper on Backed vs. Native Deposit Tokens."
theme: minima
markdown: kramdown
include:
  - googleabcdef1234567890.html
